<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<PlatformTarget>x64</PlatformTarget>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Assets\boxes.png" />
		<None Remove="Assets\boxvideo.mp4" />
		<None Remove="Assets\ocrvideo.mp4" />
		<None Remove="Assets\plcommpro.dll" />
		<None Remove="Assets\reader.py" />
		<None Remove="Assets\receipt.png" />
		<None Remove="Assets\Weights\customBoxCount.onnx" />
		<None Remove="Assets\Weights\YoloBox.onnx" />
		<None Remove="Images\innovent.ico" />
		<None Remove="Resources\Audio\warning.wav" />
		<None Remove="Resources\Images\camera.png" />
		<None Remove="Resources\Images\clock.png" />
		<None Remove="Resources\Images\close.png" />
		<None Remove="Resources\Images\dotnet_bot.png" />
		<None Remove="Resources\Images\human.png" />
		<None Remove="Resources\Images\humidity.png" />
		<None Remove="Resources\Images\motor.png" />
		<None Remove="Resources\Images\off_indicator.png" />
		<None Remove="Resources\Images\on_indicator.png" />
		<None Remove="Resources\Images\open.png" />
		<None Remove="Resources\Images\palet.png" />
		<None Remove="Resources\Images\sensor.png" />
		<None Remove="Resources\Images\temperature.png" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\boxes.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\boxvideo.mp4">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\DLL\libareacode.dll" />
		<Content Include="Assets\DLL\plcommpro.dll">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\DLL\plcomms.dll">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\DLL\plcommutils.dll">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\DLL\plrscagent.dll">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\DLL\plrscomm.dll">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\DLL\pltcpcomm.dll">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\DLL\plusbcomm.dll">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\DLL\ZKCommuCryptoClient.dll">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\ocrvideo.mp4">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\ocr_api.py">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\plcommpro.dll">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\reader.py">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\receipt.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Weights\YoloBox.onnx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Images\innovent.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Audio\pallet.wav">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Audio\shutter.mp3">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<!-- Copy EVERY file that lives in the Assets folder -->
		<None Include="Assets\**\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
		</None>
	</ItemGroup>
	<ItemGroup>
		<Content Include="Resources\Audio\warning.wav">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Images\temperature.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Content Include="Resources\Images\camera.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Images\clock.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Images\close.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Images\dotnet_bot.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Images\human.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Images\humidity.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Images\motor.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Images\off_indicator.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Images\on_indicator.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Images\open.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Images\palet.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Images\sensor.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.1" />
		<PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.18.0" />


		<PackageReference Include="NAudio" Version="2.2.1" />


		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta14" />
		<PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
		<PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
		<PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.11.0.20250507" />
		<PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.8" />
		<PackageReference Include="System.Device.Gpio" Version="4.0.1" />
		<PackageReference Include="System.IO.Ports" Version="10.0.1" />
		<PackageReference Include="Tesseract" Version="4.1.1" />
		<PackageReference Include="Tesseract.Data.English" Version="4.0.0" />
		<PackageReference Include="Yolov5Net" Version="1.1.0" />
		<PackageReference Include="Material.Icons.WPF" Version="2.1.10" />
		<PackageReference Include="MaterialDesignThemes" Version="5.1.0" />
		<PackageReference Include="Dynamsoft.DotNet.CaptureVision.Bundle" Version="3.0.6000" />
	</ItemGroup>
	<ItemGroup>


		<ProjectReference Include="..\src\Yolov5Net.Scorer\Yolov5Net.Scorer.csproj" />
	</ItemGroup>


	<ItemGroup>
		<None Update="Assets\test.jpg">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Assets\Weights\customBoxCountOld.onnx">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Assets\Weights\yolov5n.onnx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Assets\Weights\yolov5n6.onnx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Assets\Weights\yolov5s.onnx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>



	<ItemGroup>
		<Content Include="Assets\Weights\customBoxCount.onnx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>



	<ItemGroup>
	  <None Remove="Assets\DLL\libareacode.dll" />
	  <None Remove="Assets\DLL\plcommpro.dll" />
	  <None Remove="Assets\DLL\plcomms.dll" />
	  <None Remove="Assets\DLL\plcommutils.dll" />
	  <None Remove="Assets\DLL\plrscagent.dll" />
	  <None Remove="Assets\DLL\plrscomm.dll" />
	  <None Remove="Assets\DLL\pltcpcomm.dll" />
	  <None Remove="Assets\DLL\plusbcomm.dll" />
	  <None Remove="Assets\DLL\ZKCommuCryptoClient.dll" />
	  <None Remove="Assets\ocr_api.py" />
	  <None Remove="Assets\Weights\customBoxCount.onnx" />
	  <None Remove="Resources\Audio\shutter.mp3" />
	</ItemGroup>



	<ItemGroup>
	  <None Remove="Resources\Audio\pallet.wav" />
	</ItemGroup>



	<ItemGroup>
	  <COMReference Include="zkemkeeper">
	    <VersionMinor>0</VersionMinor>
	    <VersionMajor>1</VersionMajor>
	    <Guid>fe9ded34-e159-408e-8490-b720a5e632c7</Guid>
	    <Lcid>0</Lcid>
	    <WrapperTool>tlbimp</WrapperTool>
	    <Isolated>false</Isolated>
	    <EmbedInteropTypes>False</EmbedInteropTypes>
	  </COMReference>
	</ItemGroup>



	<ItemGroup>
	  <Reference Include="Basler.Pylon">
	    <HintPath>Assets\Basler.Pylon.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
